monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/main.log"
            level: debug
            channels: ["!event", "!musement_api", "!weather_api"]

        musement_api:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/musement_api.log"
            level: debug
            channels: ["musement_api"]

        weather_api:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/weather_api.log"
            level: debug
            channels: [ "weather_api" ]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
