services:
    musement_api_http_client:
        autoconfigure: true
        class: Symfony\Component\HttpClient\ScopingHttpClient
        factory: ['Symfony\Component\HttpClient\ScopingHttpClient', 'forBaseUri']
        arguments:
            - !service
                class: Symfony\Contracts\HttpClient\HttpClientInterface
                factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
                tags:
                    - { name: http_client.client }
            - '%env(MUSEMENT_API_URL)%'
        tags:
            - { name: monolog.logger, channel: musement_api }

    weather_api_http_client:
        autoconfigure: true
        class: Symfony\Component\HttpClient\ScopingHttpClient
        factory: [ 'Symfony\Component\HttpClient\ScopingHttpClient', 'forBaseUri' ]
        arguments:
            - !service
                class: Symfony\Contracts\HttpClient\HttpClientInterface
                factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
                tags:
                    - { name: http_client.client }
            - '%env(WEATHER_API_URL)%'
        tags:
            - { name: monolog.logger, channel: weather_api }

